name: Daily Scrape Job

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x' # specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decrypt and Run the scraper script
        env:
          DECRYPTOR: ${{ secrets.DECRYPTOR }}
        run: |
          ./decrypt_secrets.sh
          ls ./secrets.json
          python news_collectordb.py  # update this path to your script
