name: Daily Scrape Job

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x' # specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the scraper script
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }} # Firebase credentials file
      run: |
        python news_collectordb # update this path to your script
