name: Daily Scrape Job

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x' # specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decrypt and Run the scraper script
        env:
          DECRYPTOR: ${{ secrets.DECRYPTOR }}
        run: |
          ./decrypt_secrets.sh
          ls ./secrets.json
          python news_collectordb.py  # update this path to your script

      - name: Commit database changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add stock_news.db  # Adjust this path if needed
          git commit -m "Update stock_news.db with new data" || echo "No changes to commit"

      - name: Push changes to GitHub
        run: |
          git push origin HEAD:main # Adjust the branch name if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
